import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,patch,post} from './api';
import {useIdentity,type Role} from './Auth';
import {Badge,Panel} from './components';
import type {DeploymentStatus} from './WorkspaceStatus';
import './admin.css';
type User={id:string;email:string;name:string;requested_role:Role;role:Role|null;division:string|null;confirmed_at:string|null};
type Listing={users:User[];page:number;has_more:boolean};
type Event={id:string;at:string;kind:string;record_id:string;data:{actor:string;reason?:string;previous_role?:string;assigned_role?:string}};
const roles:Role[]=['viewer','planner','officer','admin'];

export function AdminPage(){
 const identity=useIdentity(),cache=useQueryClient(),allowed=identity.role==='admin';
 const [page,setPage]=useState(1),[search,setSearch]=useState(''),[selected,setSelected]=useState<User|null>(null),[assigned,setAssigned]=useState<Role|''>('viewer'),[reason,setReason]=useState('');
 const [email,setEmail]=useState(''),[name,setName]=useState(''),[requested,setRequested]=useState<Role>('viewer'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const users=useQuery({queryKey:['admin-users',page],queryFn:()=>api<Listing>(`/api/admin/users?page=${page}`),enabled:allowed,retry:false});
 const audit=useQuery({queryKey:['admin-audit'],queryFn:()=>api<Event[]>('/api/admin/audit?limit=100'),enabled:allowed});
 const status=useQuery({queryKey:['workspace-status'],queryFn:()=>api<DeploymentStatus>('/api/status'),enabled:allowed});
 const execute=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setNotice('');try{await fn();setNotice(message);await cache.invalidateQueries({queryKey:['admin-users']});await cache.invalidateQueries({queryKey:['admin-audit']})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 if(!allowed)return <p className="error" role="alert">Administrator access is required to manage users.</p>;
 const visible=users.data?.users.filter(u=>(u.name+' '+u.email).toLowerCase().includes(search.toLowerCase()))||[];
 return <div className="admin-page"><div className="page-heading"><div><span className="section-overline">ADMINISTRATION · {identity.division}</span><h1>User access</h1><p>Review accounts, assign permissions and inspect access decisions.</p></div><button onClick={()=>{void users.refetch();void audit.refetch()}}>Refresh access records</button></div>
 {notice&&<p className="validation-pass" role="status">{notice}</p>}{(error||users.error)&&<p className="error" role="alert">{error||users.error?.message}</p>}
 <Panel title="Invite a colleague"><form className="padded admin-invite" onSubmit={e=>{e.preventDefault();void execute(async()=>{const result=await post<{message:string}>('/api/admin/invitations',{email,name,requested_role:requested});setEmail('');setName('');return result},'Invitation sent. Review access after the recipient confirms their email.')}}><p>The recipient will receive an email invitation. Sending an invitation does not grant workspace access.</p><label>Colleague name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Invitation email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Proposed role<select value={requested} onChange={e=>setRequested(e.target.value as Role)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><button className="primary" disabled={busy||!status.data?.user_administration||!name.trim()}>Send invitation email</button></form></Panel>
 <Panel title="Access review" aside={<Badge>Page {page}</Badge>}><div className="padded"><p>Requested roles are preferences. Only a confirmed, assigned account can open this division. Other divisions’ accounts are excluded.</p><label>Filter this page<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or email"/></label></div><div className="table-scroll"><table className="admin-users"><thead><tr><th>User</th><th>Requested</th><th>Assigned role</th><th>Division</th><th>Email</th><th>Action</th></tr></thead><tbody>{visible.map(u=><tr key={u.id}><td><strong>{u.name||'Name not provided'}</strong><small>{u.email}</small></td><td>{roles.includes(u.requested_role)?u.requested_role:'Unrecognized request'}</td><td>{u.role||'Awaiting approval'}</td><td>{u.division||'Unassigned'}</td><td>{u.confirmed_at?'Confirmed':'Awaiting confirmation'}</td><td><button disabled={busy} onClick={()=>{setSelected(u);setAssigned(u.role||'viewer');setReason('');setError('')}}>Review access</button></td></tr>)}</tbody></table></div>{users.isPending?<p className="padded" role="status">Loading accounts…</p>:!visible.length&&<p className="empty">No matching accounts on this page. Continue to the next page if available.</p>}<div className="toolbar padded"><button disabled={page===1||busy} onClick={()=>setPage(page-1)}>Previous accounts</button><button disabled={!users.data?.has_more||busy} onClick={()=>setPage(page+1)}>Next accounts</button></div></Panel>
 {selected&&<Panel title={`Review access for ${selected.email}`}><form className="padded admin-review" onSubmit={e=>{e.preventDefault();void execute(async()=>{await patch(`/api/admin/users/${selected.id}`,{role:assigned||null,expected_role:selected.role,expected_division:selected.division,reason});setSelected(null)},'Access saved. Active sessions recheck their role within 30 seconds or on tab focus.')}}><p>Current assignment: {selected.role||'No access'}. Target division: {identity.division}.</p><label>Assigned role<select aria-label="Assigned role" value={assigned} onChange={e=>setAssigned(e.target.value as Role|'')}><option value="">Remove workspace access</option>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Access change reason<textarea required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{selected.id===identity.id&&<p>Your own administrator access is protected. Ask a second administrator to change it.</p>}{!selected.confirmed_at&&<p>Email confirmation is required before granting access.</p>}<div className="toolbar"><button className="primary" disabled={busy||reason.trim().length<3||(selected.id===identity.id&&assigned!=='admin')||(!selected.confirmed_at&&!!assigned)}>{assigned?'Confirm access assignment':'Confirm access removal'}</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>Cancel review</button></div></form></Panel>}
 <Panel title="Audit history"><p className="padded">Latest 100 recorded events. Access attempts and confirmed changes are shown separately; an unconfirmed change needs reconciliation with the account record.</p>{audit.error&&<p className="error">{audit.error.message}</p>}<div className="table-scroll"><table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Target</th><th>Reason / assignment</th></tr></thead><tbody>{audit.data?.slice().reverse().map(e=><tr key={e.id}><td>{new Date(e.at).toLocaleString()}</td><td>{e.kind}</td><td><code>{e.data.actor}</code></td><td><code>{e.record_id}</code></td><td>{e.data.reason||'—'}{e.kind==='user-access-updated'&&<small>{e.data.previous_role||'None'} → {e.data.assigned_role||'No access'}</small>}</td></tr>)}</tbody></table></div></Panel>
 <Panel title="Deployment services"><dl className="padded">{status.data&&Object.entries({Database:status.data.database,'Workspace updates':status.data.updates,'Realtime subscriptions':status.data.realtime,'Source connections':status.data.source_connections,'External AI':status.data.external_ai,'MFA for operational roles':status.data.mfa_enforced?'Required':'Not required in this environment','Signup screen':status.data.public_signup?'Enabled; Supabase settings also apply':'Invitation only'}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></Panel>
 </div>
}
