import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,post} from './api';
import {Panel,Badge} from './components';
import {useIdentity,usePermission} from './Auth';

type Status={enabled:boolean;model:string;data_policy:string;daily_call_limit:number;optimizer:string;nlp:string};
type Result={id:string;model:string;review_required:boolean;output:{summary?:string;findings?:{finding:string;evidence_ids:string[]}[];fields?:{field:string;value:string;quote:string}[];uncertainties:string[]}};
type Model={id:string;snapshot_id:string;algorithm:string;mae_minutes:number;engineering_baseline_mae:number;training_ids:string[];holdout_ids:string[];synthetic:boolean;limitation:string};
type AutomationData={config:{enabled:boolean;interval_minutes:number;prepare_reports:boolean};runs:{id:string;created_at:string;status:string;alerts:unknown[];report_ids:string[]}[]};

export function AIAssist({target,id}:{target:'recommendations'|'reports';id:string}){
 const status=useQuery({queryKey:['ai-status'],queryFn:()=>api<Status>('/api/ai/status')});
 const can=usePermission('planner');const [result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <details className="ai-tools"><summary>AI {target==='reports'?'report summary':'explanation'}</summary><div className="padded"><p>{status.data?.enabled?`Model: ${status.data.model}. This sends the saved evidence to the configured AI provider and creates a separate draft for review.`:'LLM assistance is disabled. Add the server-side key, model and data policy to enable it. Local analysis remains available.'}</p><button title={!can?'Planner access required':undefined} disabled={!can||!status.data?.enabled||busy} onClick={async()=>{setBusy(true);setError('');try{setResult(await post<Result>(`/api/ai/${target}/${id}/${target==='reports'?'summary':'explain'}`))}catch(e){setError(String(e))}finally{setBusy(false)}}}>{busy?'Preparing AI draft…':'Generate AI draft'}</button>{error&&<p role="alert" className="error">{error}</p>}{result&&<AIResult result={result}/>}</div></details>;
}

function AIResult({result}:{result:Result}){return <div className="ai-result"><strong>AI draft · Officer review required</strong>{result.output.summary&&<p>{result.output.summary}</p>}{result.output.findings?.map((f,i)=><p key={i}>{f.finding}<br/><small>Evidence: {f.evidence_ids.join(', ')}</small></p>)}{result.output.fields?.map((f,i)=><p key={i}><strong>{f.field}: {f.value}</strong><br/>Source: “{f.quote}”</p>)}{!!result.output.uncertainties.length&&<ul>{result.output.uncertainties.map((v,i)=><li key={i}>{v}</li>)}</ul>}<small>{result.model} · Saved draft {result.id.slice(0,8)}. Verify the interpretation against the source records.</small></div>}

export function AIWorkbench({snapshotId}:{snapshotId:string}){
 const query=useQueryClient(),identity=useIdentity(),can=usePermission('planner');
 const status=useQuery({queryKey:['ai-status'],queryFn:()=>api<Status>('/api/ai/status')});
 const models=useQuery({queryKey:['duration-models'],queryFn:()=>api<Model[]>('/api/ai/models')});
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[text,setText]=useState(''),[result,setResult]=useState<Result|null>(null);
 const latest=models.data?.find(m=>m.snapshot_id===snapshotId);
 const run=async(name:string,fn:()=>Promise<unknown>)=>{setBusy(name);setError('');try{await fn();await query.invalidateQueries({queryKey:['duration-models']})}catch(e){setError(String(e))}finally{setBusy('')}};
 return <div className="ai-tools"><Panel title="AI services and learning" aside={<Badge>{status.data?.enabled?'LLM configured':'Local intelligence active'}</Badge>}><div className="padded"><div className="ai-status"><span>Optimizer: {status.data?.optimizer||'Loading'}</span><span>External AI policy: {status.data?.data_policy||'Loading'}</span></div><h3>Duration model experiment</h3><p>Train ridge regression on completed outcomes and compare it with engineering estimates on later records. Evaluation results are saved; model training does not change the approved planning policy.</p><button title={!can?'Planner access required':undefined} disabled={!can||!!busy} onClick={()=>run('Training',()=>post(`/api/ai/models/${snapshotId}/train`))}>{busy==='Training'?'Training and evaluating…':'Train and evaluate duration model'}</button>{latest&&<div className="ai-result"><p>{latest.algorithm} · {latest.synthetic?'Synthetic data':'Imported data'}</p><p>{latest.training_ids.length} training records · {latest.holdout_ids.length} holdout records</p><p>Model MAE: <strong>{latest.mae_minutes} min</strong> · Engineering baseline MAE: <strong>{latest.engineering_baseline_mae} min</strong></p><p>{latest.limitation}</p></div>}<h3>LLM incident analysis</h3><p>Extract cause, asset, location, severity and impact only where the narrative supports them. Sending free text requires the server's authorized-data policy. The local narrative analyzer below works without a key.</p><label>Text for external AI review<textarea value={text} maxLength={5000} onChange={e=>setText(e.target.value)}/></label><button title={!can?'Planner access required':undefined} disabled={!can||!!busy||!status.data?.enabled||status.data.data_policy!=='authorized'||text.trim().length<3} onClick={()=>run('NLP',async()=>setResult(await post<Result>(`/api/ai/nlp/${snapshotId}`,{text})))}>{busy==='NLP'?'Analyzing…':'Send text for AI extraction'}</button>{result&&<AIResult result={result}/>}<p className="muted">Configured model: {status.data?.model||'None'} · Maximum {status.data?.daily_call_limit??0} external calls per UTC day. Generated text cannot approve or dispatch work.</p>{(error||status.error||models.error)&&<p className="error" role="alert">{error||status.error?.message||models.error?.message}</p>}</div></Panel>{identity.role==='admin'&&<AutomationPanel/>}</div>;
}

function AutomationPanel(){
 const query=useQueryClient();const data=useQuery({queryKey:['automation'],queryFn:()=>api<AutomationData>('/api/admin/automation'),refetchInterval:30000});
 const [enabled,setEnabled]=useState<boolean|null>(null),[reports,setReports]=useState<boolean|null>(null),[interval,setInterval]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const config=data.data?.config;
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await query.invalidateQueries({queryKey:['automation']});setEnabled(null);setReports(null);setInterval(null)}catch(e){setError(String(e))}finally{setBusy(false)}};
 return <Panel title="Scheduled monitoring and report preparation"><div className="padded"><p>Monitor the current source evidence and prepare MIS/PAM drafts for current, approved recommendations. New execution outcomes produce new drafts. This does not synchronize upstream feeds or take operational action.</p><div className="automation-config"><label className="check"><input type="checkbox" checked={enabled??config?.enabled??false} onChange={e=>setEnabled(e.target.checked)}/>Enable schedule</label><label className="check"><input type="checkbox" checked={reports??config?.prepare_reports??false} onChange={e=>setReports(e.target.checked)}/>Prepare report drafts</label><label>Interval (minutes)<input type="number" min={5} max={1440} value={interval??config?.interval_minutes??30} onChange={e=>setInterval(Number(e.target.value))}/></label><button disabled={busy||!config} onClick={()=>act(()=>post('/api/admin/automation/config',{enabled:enabled??config!.enabled,prepare_reports:reports??config!.prepare_reports,interval_minutes:interval??config!.interval_minutes}))}>Save automation settings</button><button disabled={busy||!config} onClick={()=>act(()=>post('/api/admin/automation/run'))}>Run monitoring now</button></div>{(error||data.error)&&<p className="error" role="alert">{error||data.error?.message}</p>}<div className="table-scroll"><table><thead><tr><th>Run</th><th>Status</th><th>Alerts</th><th>New drafts</th></tr></thead><tbody>{data.data?.runs.slice(0,8).map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.status}</td><td>{r.alerts.length}</td><td>{r.report_ids.length}</td></tr>)}</tbody></table></div></div></Panel>;
}
