import {AIAssist,AIWorkbench} from './AITools';
import {DownloadLink} from './Auth';
import {useState, type FormEvent} from 'react';
import {NavLink,useSearchParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,post,job,API,time} from './api';
import {Badge,Panel,Sheet} from './components';
import type {Draft,Evidence,Extraction,InsightRow,Recommendation,Workspace} from './intelligenceTypes';
import './intelligence.css';

const base='/api/intelligence';
type Act=(label:string,fn:()=>Promise<unknown>)=>Promise<void>;
type Props={snapshotId:string;horizon:7|30;day:number;view:'queue'|'operations'|'insights'|'reports'};

export function DecisionWorkspace({snapshotId,horizon,day,view}:Props){
 const query=useQueryClient();const [params,setParams]=useSearchParams();const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 const workspace=useQuery({queryKey:['intelligence',snapshotId],queryFn:()=>api<Workspace>(`${base}/workspace?snapshot_id=${snapshotId}`)});
 const [selected,setSelected]=useState<InsightRow|null>(null);
 const act:Act=async(label,fn)=>{if(busy)return;setBusy(label);setError('');setMessage('');try{await fn();await query.invalidateQueries({queryKey:['intelligence']});await query.invalidateQueries({queryKey:['recommendation']});await query.invalidateQueries({queryKey:['reports']});setMessage(label+' completed.')}catch(e){setError(String(e instanceof Error?e.message:e))}finally{setBusy('')}};
 const w=workspace.data;
 const chosen=params.get('recommendation')||w?.recommendations[0]?.id;
 const recommendation=useQuery({queryKey:['recommendation',chosen],queryFn:()=>api<Recommendation>(`${base}/recommendations/${chosen}`),enabled:!!chosen});
 const rec=recommendation.data;
 const pick=(id:string)=>setParams(p=>{const next=new URLSearchParams(p);next.set('recommendation',id);return next});
 const generate=(task_id?:string,window_id?:string,reason?:string)=>act('Recommendation',async()=>{const id=await job(base+'/recommend',{snapshot_id:snapshotId,evidence_id:w!.evidence.id,horizon,day,task_id,window_id,reason:reason||''});pick(id)});
 if(workspace.error)return <div className="error" role="alert">{workspace.error.message}<button onClick={()=>workspace.refetch()}>Retry evidence</button></div>;
 if(!w)return <p className="loading">Loading decision-support evidence…</p>;
 const active=rec?.source_snapshot_id===snapshotId?rec:undefined;
 return <div className="decision-workspace">
  <div className="advisory-note"><div><strong>{w.mode}</strong><span>{w.evidence.division} · Evidence time {new Date(w.evidence.as_of).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</span></div><p>Recommendations support officer review. Existing operational systems retain control.</p></div>
  {busy&&<div role="status" className="info">{busy}…</div>}{message&&<div role="status" className="validation-pass">{message}</div>}{(error||recommendation.error)&&<div role="alert" className="error">{error||recommendation.error?.message}</div>}
  {view==='queue'&&<>
   <div className="decision-toolbar"><div><button className="primary" disabled={!!busy||w.feeds.some(f=>f.state!=='available')} onClick={()=>generate()}>Recommend block plan</button><NavLink className="button" to={{pathname:'/tasks',search:params.toString()}}>Maintenance requests</NavLink></div><label>Saved recommendation<select aria-label="Saved recommendation" value={active?.id||''} onChange={e=>pick(e.target.value)}><option value="" disabled>Select recommendation</option>{w.recommendations.map(r=><option key={r.id} value={r.id}>{r.id.slice(0,8)} · {r.review_status}{r.current?'':' · superseded'}</option>)}</select></label></div>
   {w.feeds.some(f=>f.state!=='available')&&<p className="error">Refresh missing or stale evidence in Operations before requesting a plan.</p>}
   {active&&<RecommendationReview rec={active} w={w} busy={busy} act={act} generate={generate}/>}
   <Queue key={snapshotId+":"+day+":"+horizon} w={w} rec={active} day={day} horizon={horizon} inspect={setSelected}/>
  </>}
  {view==='operations'&&<Operations w={w} day={day} busy={busy} act={act}/>}
  {view==='insights'&&<><AIWorkbench snapshotId={snapshotId}/><Insights w={w} busy={busy} act={act} inspect={setSelected}/></>}
  {view==='reports'&&<Reporting w={w} rec={active} busy={busy} act={act}/>}
  <Sheet open={!!selected} onClose={()=>setSelected(null)} title={selected?`Evidence for ${selected.task_id}`:'Work evidence'} wide>{message&&<p role="status" className="validation-pass">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}{selected&&<EvidenceDetails key={selected.task_id+':'+w.evidence.id} row={selected} w={w} busy={busy} act={act}/>}</Sheet>
 </div>
}

function Queue({w,rec,day,horizon,inspect}:{w:Workspace;rec?:Recommendation;day:number;horizon:number;inspect:(r:InsightRow)=>void}){
 const [search,setSearch]=useState(''),[page,setPage]=useState(0);const rows=(rec?.rows||w.rows).filter(r=>r.earliest<(day+horizon)*1440&&(r.due>=day*1440||r.mandatory||r.due<0)&&(r.title+' '+r.task_id+' '+r.section).toLowerCase().includes(search.toLowerCase()));
 return <Panel title="Block queue" aside={<Badge>{rows.length} work items</Badge>}><div className="queue-intro"><p>Priority factors are officer inputs. A range means an assessment is incomplete; mandatory work remains a hard constraint.</p><label>Find work<input placeholder="Task, section or description" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label></div><div className="table-scroll"><table className="queue-table"><thead><tr><th>Work requirement</th><th>Priority / score</th><th>Duration estimate</th><th>Recommended work interval</th><th>Review items</th></tr></thead><tbody>{rows.slice(page*12,page*12+12).map(r=><tr key={r.task_id}><td data-label="Work requirement"><button className="text-button" onClick={()=>inspect(r)}>{r.task_id} · {r.title}</button><small>{r.section} · {r.department}{r.mandatory?' · Mandatory':''}</small></td><td data-label="Priority"><Badge tone={r.priority.level==='High'?'warn':'neutral'}>{r.priority.level}</Badge><small>{r.priority.score??`${r.priority.score_low}–${r.priority.score_high}`} / 100{r.priority.score===null?' · incomplete':''}</small></td><td data-label="Duration estimate">{r.duration.high===null?'No statistical range':`${r.duration.low}–${r.duration.high} min`}<small>{r.duration.planned} min engineering estimate · {r.duration.samples} outcomes</small></td><td data-label="Recommended interval">{r.recommendation?<><strong>{r.recommendation.window_id}</strong><small>{time(r.recommendation.start,w.anchor,true)}–{time(r.recommendation.end,w.anchor)} IST</small></>:<span>{rec?'Unassigned':'Awaiting plan'}</span>}</td><td data-label="Review items">{r.risks.slice(0,2).map(v=><small key={v}>{v}</small>)}<button className="text-button" onClick={()=>inspect(r)}>Review evidence</button></td></tr>)}</tbody></table></div>{!rows.length&&<p className="empty">No work matches this date range and search.</p>}<div className="queue-pagination"><span>{rows.length?`${page*12+1}–${Math.min(page*12+12,rows.length)} of ${rows.length}`:'0 work items'}</span><button disabled={page===0} onClick={()=>setPage(page-1)}>Previous work</button><button disabled={(page+1)*12>=rows.length} onClick={()=>setPage(page+1)}>Next work</button></div></Panel>
}

function RecommendationReview({rec,w,busy,act,generate}:{rec:Recommendation;w:Workspace;busy:string;act:Act;generate:(task?:string,window?:string,reason?:string)=>Promise<void>}){
 const [reason,setReason]=useState(''),[task,setTask]=useState(''),[window,setWindow]=useState('');
 const windows=w.rows.find(r=>r.task_id===task)?.windows||[];
 const possible=rec.plan.validation.valid&&['OPTIMAL','FEASIBLE'].includes(rec.plan.solver_status);
 return <section className="recommendation-review"><div className="recommendation-heading"><div><span className="section-overline">RECOMMENDATION {rec.id.slice(0,8)}</span><h2>{possible?`${rec.plan.assignments.length} work items in ${rec.plan.packages.length} block packages`:'No feasible recommendation to approve'}</h2></div><div><Badge tone={rec.current?'neutral':'warn'}>{rec.current?'Current evidence':'Evidence changed'}</Badge><Badge>{rec.review_status}</Badge></div></div><p className="muted">{rec.methodology}. {rec.plan.solver_status}. Duration allowances are modeled estimates, not guarantees.</p>
 {!possible&&<div className="error">{rec.plan.validation.violations.map(v=><p key={v.rule_id+v.records.join()}>{v.records.join(', ')}: {v.message}</p>)}</div>}
 <div className="review-controls"><label>Officer review reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Record your assessment, uncertainties and decision"/></label><div className="review-buttons"><button className="primary" disabled={!!busy||!possible||!rec.current||rec.review_status!=='pending'||reason.trim().length<3} onClick={()=>act('Approval',()=>post(`${base}/recommendations/${rec.id}/decision`,{action:'approve',reason}))}>Approve recommendation</button><button disabled={!!busy||rec.review_status!=='pending'||reason.trim().length<3} onClick={()=>act('Rejection',()=>post(`${base}/recommendations/${rec.id}/decision`,{action:'reject',reason}))}>Reject recommendation</button><NavLink className="text-button" to={`/planner?corridor=${encodeURIComponent(w.corridor)}&plan=${rec.plan_id}`}>Inspect saved schedule</NavLink></div></div>
 <AIAssist target="recommendations" id={rec.id}/><details className="modify-recommendation"><summary>Modify a recommended window</summary><p>Choose a task and window. The full constraint model runs again; the result remains pending officer review.</p><div className="form"><label>Work item<select aria-label="Modify work item" value={task} onChange={e=>{setTask(e.target.value);setWindow('')}}><option value="">Choose task</option>{w.rows.map(r=><option key={r.task_id} value={r.task_id}>{r.task_id} · {r.title}</option>)}</select></label><label>Requested window<select value={window} onChange={e=>setWindow(e.target.value)}><option value="">Choose window</option>{windows.map(v=><option key={v.id}>{v.id}</option>)}</select></label><button disabled={!!busy||!task||!window||reason.trim().length<3} onClick={()=>generate(task,window,reason)}>Recompute modification</button></div></details>
 {!!rec.events.filter(e=>e.data.reason).length&&<details><summary>Decision history</summary>{rec.events.filter(e=>e.data.reason).map(e=><p key={e.id}>{e.kind} · {e.data.reason}</p>)}</details>}
 </section>
}

function EvidenceDetails({row,w,busy,act}:{row:InsightRow;w:Workspace;busy:string;act:Act}){
 const [factors,setFactors]=useState<Record<string,number|null>>(w.evidence.assessments[row.task_id]||Object.fromEntries(row.priority.factors.map(f=>[f.key,f.value])));
 const history=[...w.evidence.history,...w.outcomes.map(o=>o.history)].filter(h=>row.duration.evidence_ids.includes(h.id));
 return <div className="evidence-details"><h2>{row.title}</h2><p>{row.section} · {row.source} / {row.source_record_id||'Missing source ID'}</p><h3>Priority assessment</h3><p>0 = no assessed impact; 5 = highest assessed impact. Blank means unknown. Policy weights are demonstration settings, not official railway rules.</p><div className="factor-grid">{row.priority.factors.map(f=><label key={f.key}>{f.label}<span className="muted">Weight {f.weight}%</span><input aria-label={f.label} type="number" min={0} max={5} step={1} value={factors[f.key]??''} onChange={e=>setFactors({...factors,[f.key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}</div><button disabled={!!busy} onClick={()=>act('Assessment saved',()=>post(base+'/evidence',{expected_evidence:w.evidence.id,evidence:{...w.evidence,assessments:{...w.evidence.assessments,[row.task_id]:factors}}}))}>Save priority assessment</button><p className="muted">Security of the defect is preserved from your workflow; its operational definition still needs confirmation. Saving invalidates earlier recommendations.</p>
 <h3>Duration and uncertainty</h3><p>{row.duration.method}. {row.duration.confidence}; {row.duration.samples} matched outcomes. Planning allowance: {row.duration.planning_minutes} minutes.</p><p>These historical intervals are not calibrated confidence bounds or accident-risk probabilities.</p><div className="table-scroll"><table><thead><tr><th>Evidence</th><th>Planned</th><th>Actual</th><th>Weather</th><th>Source narrative</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{h.id}</td><td>{h.planned_minutes} min</td><td>{h.actual_minutes} min</td><td>{h.weather}</td><td>{h.narrative}</td></tr>)}</tbody></table></div>
 <h3>Dependencies and work combinations</h3>{row.dependencies.map((d,i)=><p key={i}><strong>{d.kind} · {d.record}</strong>: {d.detail}</p>)}<p>Potential same-section combinations: {row.combination_candidates.join(', ')||'None'}. Compatibility still requires a joint solve; use Opportunities to test bundles.</p>
 <h3>Window evidence</h3>{row.windows.map(v=><div className="window-evidence" key={v.id}><strong>{v.id} · {time(v.start,w.anchor,true)}–{time(v.end,w.anchor)} IST</strong><p>{v.eligibility_issue||'Basic access eligibility matched; joint scheduling still required.'}</p>{v.conflicts.map(c=><p key={c.kind+c.record}>{c.kind}: {c.record} overlaps part of this source window.</p>)}{v.weather.map(c=><p key={c.id}>{c.id}: {c.condition} · {time(c.start,w.anchor)}–{time(c.end,w.anchor)} · {c.planning_hold?'Planning hold':'Advisory'} · {c.reason}</p>)}{v.cautions.map(c=><p key={c.id}>{c.id}: {c.description} · {c.work_prohibited?'Work prohibited':'Officer review required'}</p>)}</div>)}
 </div>
}

function Operations({w,day,busy,act}:{w:Workspace;day:number;busy:string;act:Act}){
 const [upload,setUpload]=useState<Evidence|null>(null),[uploadError,setUploadError]=useState('');
 const read=async(file?:File)=>{setUpload(null);setUploadError('');if(!file)return;try{if(file.size>5*1024*1024)throw Error('Maximum evidence file size is 5 MB');const value=JSON.parse(await file.text());if(!Array.isArray(value.feeds)||!Array.isArray(value.history)||!value.snapshot_id)throw Error('Use the downloadable evidence contract');setUpload(value)}catch(e){setUploadError(String(e))}};
 return <div className="operations-workspace"><div className="feed-grid">{w.feeds.map(f=><article key={f.source}><span className="section-overline">{f.source}</span><h2>{f.state==='available'?'Evidence available':f.state}</h2><p>{f.age_minutes===null?'No received timestamp':`${f.age_minutes} min old at evidence clock`}</p><small>{w.evidence.synthetic?'Synthetic source fixture':'Imported source export'} · No live connector</small></article>)}</div><p className="muted">{w.integration}</p>
 <Panel title="Source evidence"><div className="padded"><p>COA-style blocks, cautions and movements inform access constraints. ROAMS-style maintenance requests can be imported in Data review. This screen shows planning inputs rather than reproducing CCMIS reporting.</p><div className="toolbar"><DownloadLink className="button" href={`${API}${base}/evidence/${w.snapshot_id}/sample`}>Download evidence JSON</DownloadLink><label>Import evidence JSON<input type="file" accept=".json" onChange={e=>read(e.target.files?.[0])}/></label></div>{uploadError&&<p role="alert" className="error">{uploadError}</p>}{upload&&<div className="import-review"><p>Snapshot {upload.snapshot_id} · {upload.feeds.length} feeds · {upload.history.length} completed outcomes. {upload.synthetic?'Synthetic':'Imported'} evidence will create a new version and supersede existing recommendations.</p><button disabled={!!busy} onClick={()=>act('Evidence import',async()=>{await post(base+'/evidence',{expected_evidence:w.evidence.id,evidence:upload});setUpload(null)})}>Validate and import evidence</button></div>}</div></Panel>
 <PeriodTable title="Existing block reservations" rows={w.evidence.blocks} anchor={w.anchor}/><PeriodTable title="Caution orders" rows={w.evidence.cautions} anchor={w.anchor}/><PeriodTable title="Weather conditions and holds" rows={w.evidence.weather} anchor={w.anchor}/>
 <Panel title="Train occupancy inputs"><div className="table-scroll"><table><thead><tr><th>Train</th><th>Type</th><th>Section</th><th>Protected movement interval</th></tr></thead><tbody>{w.movements.flatMap(m=>m.occupancies.filter(o=>o.start<(day+1)*1440&&o.end>day*1440).map((o,i)=><tr key={m.id+i}><td>{m.id}</td><td>{m.kind}</td><td>{o.section}</td><td>{time(o.start,w.anchor,true)}–{time(o.end,w.anchor)} IST</td></tr>))}</tbody></table></div><p className="padded muted">Showing the selected day's supplied movements. Window conflicts identify affected movements; no knock-on delay simulation or train dispatch change is claimed.</p></Panel></div>
}

function PeriodTable({title,rows,anchor}:{title:string;rows:Evidence['blocks'];anchor:string}){return <Panel title={title}><div className="table-scroll"><table><thead><tr><th>Source record</th><th>Directed section</th><th>Interval IST</th><th>Condition / status</th><th>Planning implication</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.section}</td><td>{time(r.start,anchor,true)}–{time(r.end,anchor,true)}</td><td>{r.condition||r.status||(r.speed_kph?`${r.speed_kph} km/h`:'Restriction')}</td><td>{r.reason||r.description}{r.planning_hold||r.work_prohibited?' · Excludes planned work':''}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="empty">No supplied records.</p>}</Panel>}

function Insights({w,busy,act,inspect}:{w:Workspace;busy:string;act:Act;inspect:(r:InsightRow)=>void}){
 const [text,setText]=useState('Train detained due to repeated signal failure near S2-UP for 25 minutes.'),[result,setResult]=useState<Extraction|null>(null);
 const d=w.diagnostics;
 return <><div className="insight-columns"><Panel title="Review alerts" aside={<Badge>{w.alerts.length}</Badge>}><div className="alert-list">{w.alerts.slice(0,25).map(a=><article key={a.id}><span className="section-overline">{a.kind} · {a.record}</span><p>{a.message}</p></article>)}{!w.alerts.length&&<p>No baseline alert thresholds crossed.</p>}{w.alerts.length>25&&<p>Showing first 25 alerts. Download source evidence to review all records.</p>}</div></Panel><Panel title="Duration model evaluation"><div className="padded"><p>{d.method}.</p><dl><div><dt>Training records</dt><dd>{d.training_records}</dd></div><div><dt>Evaluated holdout</dt><dd>{d.evaluated} / {d.test_records}</dd></div><div><dt>Mean absolute error</dt><dd>{d.mean_absolute_error===null?'Insufficient history':`${d.mean_absolute_error} min`}</dd></div><div><dt>Empirical interval coverage</dt><dd>{d.interval_coverage===null?'Not available':`${Math.round(d.interval_coverage*100)}%`}</dd></div></dl><p>{d.limitation}</p></div></Panel></div>
 <Panel title="Delay and failure narrative analysis"><form className="padded" onSubmit={(e:FormEvent)=>{e.preventDefault();act('Narrative analysis',async()=>setResult(await post<Extraction>(`${base}/nlp/${w.snapshot_id}`,{text})))}}><label>Original incident narrative<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={5000}/></label><button disabled={!!busy||text.trim().length<3} className="primary">Analyze narrative</button></form>{result&&<div className="nlp-result"><p>{result.method}</p><blockquote>{result.original}</blockquote><div className="table-scroll"><table><thead><tr><th>Extracted cause</th><th>Category</th><th>Exact evidence</th><th>Interpretation</th></tr></thead><tbody>{result.matches.map((m,i)=><tr key={i}><td>{m.cause}</td><td>{m.category}</td><td>“{m.text}” · characters {m.start}–{m.end}</td><td>{m.negated?'Negated; do not count as a cause':'Mentioned; verify'}</td></tr>)}</tbody></table></div><p>Location: {result.locations.join(', ')||'Not identified'} · Durations mentioned: {result.durations.map(d=>d.minutes+' min').join(', ')||'None'}</p><p>Matching historical records: {result.recurring_evidence.join(', ')||'None'}</p><p>{result.uncertainty}. Severity: {result.severity}. {result.operational_impact}.</p></div>}</Panel>
 <Panel title="Historical disruption evidence"><div className="table-scroll"><table><thead><tr><th>Work</th><th>Matched section / department records</th><th>Average actual duration</th><th>Extensions</th><th>Review</th></tr></thead><tbody>{w.rows.slice(0,30).map(r=><tr key={r.task_id}><td>{r.task_id} · {r.title}</td><td>{r.history.count}</td><td>{r.history.average_actual??'Unknown'} min</td><td>{r.history.extensions}</td><td><button className="text-button" onClick={()=>inspect(r)}>Source evidence</button></td></tr>)}</tbody></table></div></Panel></>
}

function Reporting({w,rec,busy,act}:{w:Workspace;rec?:Recommendation;busy:string;act:Act}){
 const [kind,setKind]=useState('MIS'),[selected,setSelected]=useState<string|null>(null);
 const reports=useQuery({queryKey:['reports',w.snapshot_id],queryFn:()=>api<Draft[]>(`${base}/reports?snapshot_id=${w.snapshot_id}`)});
 const draft=reports.data?.find(r=>r.id===selected)||reports.data?.[0];
 return <><div className="decision-toolbar"><div><label>Draft type<select value={kind} onChange={e=>setKind(e.target.value)}><option>MIS</option><option>PAM</option></select></label><button className="primary" disabled={!!busy||!rec} onClick={()=>act('Draft preparation',async()=>{const result=await post<Draft>(base+'/reports',{recommendation_id:rec!.id,kind});setSelected(result.id)})}>Prepare report draft</button></div><label>Saved report<select aria-label="Saved report" value={draft?.id||''} onChange={e=>setSelected(e.target.value)}><option value="" disabled>Select draft</option>{reports.data?.map(r=><option key={r.id} value={r.id}>{r.kind} · {r.id.slice(0,8)} · {r.status}</option>)}</select></label></div><p className="muted">Drafts use saved recommendation {rec?.id.slice(0,8)||'—'} and recorded outcomes. Missing actuals remain blank. These are illustrative MIS/PAM drafts for officer review.</p>{reports.error&&<p className="error" role="alert">{reports.error.message}</p>}
 {rec&&<OutcomeForm key={rec.id+':'+w.outcomes.length} rec={rec} w={w} busy={busy} act={act}/>}
 {draft?<DraftReview key={draft.id+draft.reviews.length} draft={draft} busy={busy} act={act}/>:<Panel title="Report preparation"><p className="empty">Generate a recommendation in Block queue, then prepare a draft here.</p></Panel>}
 <Panel title="Recorded execution outcomes"><div className="table-scroll"><table><thead><tr><th>Work</th><th>Planned</th><th>Actual</th><th>Delay</th><th>Reported cause</th></tr></thead><tbody>{w.outcomes.map(o=><tr key={o.id}><td>{o.task_id}</td><td>{o.history.planned_minutes} min</td><td>{o.history.actual_minutes} min</td><td>{o.history.delay_minutes} min</td><td>{o.history.narrative}</td></tr>)}</tbody></table></div>{!w.outcomes.length&&<p className="empty">No actual outcomes recorded yet.</p>}<p className="padded muted">Recorded outcomes become history only when the evidence cutoff reaches their completion time. Plans are never treated as actual outcomes.</p></Panel></>
}

function OutcomeForm({rec,w,busy,act}:{rec:Recommendation;w:Workspace;busy:string;act:Act}){
 const available=rec.plan.assignments.filter(a=>!w.outcomes.some(o=>o.recommendation_id===rec.id&&o.task_id===a.task_id));
 const [task,setTask]=useState(available[0]?.task_id||''),[start,setStart]=useState(available[0]?.start||0),[end,setEnd]=useState(available[0]?.end||0),[observed,setObserved]=useState(available[0]?.end||0),[delay,setDelay]=useState(0),[weather,setWeather]=useState('clear'),[narrative,setNarrative]=useState('');
 return <Panel title="Record actual execution"><form className="outcome-form" onSubmit={e=>{e.preventDefault();act('Outcome recording',()=>post(`${base}/recommendations/${rec.id}/outcomes`,{task_id:task,actual_start:start,actual_end:end,observed_at:observed,delay_minutes:delay,weather,narrative}))}}><p>Demo observation only. Times are minutes from {new Date(w.anchor).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST; use actual recorded times.</p><div className="form"><label>Completed work<select value={task} onChange={e=>{setTask(e.target.value);const a=available.find(a=>a.task_id===e.target.value);if(a){setStart(a.start);setEnd(a.end);setObserved(a.end)}}}>{available.map(a=><option key={a.task_id}>{a.task_id}</option>)}</select></label><label>Actual start minute<input type="number" min={0} value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>Actual end minute<input type="number" min={start+1} value={end} onChange={e=>setEnd(Number(e.target.value))}/></label><label>Observed at minute<input type="number" min={end} value={observed} onChange={e=>setObserved(Number(e.target.value))}/></label><label>Recorded delay minutes<input type="number" min={0} value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label><label>Observed weather<select value={weather} onChange={e=>setWeather(e.target.value)}>{['clear','rain','heavy rain','storm','heat','fog'].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Execution narrative<textarea value={narrative} onChange={e=>setNarrative(e.target.value)}/></label><button disabled={!!busy||rec.review_status!=='approved'||!task||narrative.trim().length<3}>Save actual outcome</button>{rec.review_status!=='approved'&&<p className="muted">Approve the recommendation before recording its outcomes.</p>}</form></Panel>
}

function DraftReview({draft,busy,act}:{draft:Draft;busy:string;act:Act}){
 const [summary,setSummary]=useState(draft.summary),[reason,setReason]=useState('');
 return <Panel title={`${draft.kind} report draft`} aside={<Badge>{draft.status}</Badge>}><div className="padded"><p>{draft.method}</p><label>Officer-editable summary<textarea value={summary} onChange={e=>setSummary(e.target.value)}/></label><AIAssist target="reports" id={draft.id}/><h3>Missing fields and exceptions</h3>{draft.missing.length?<ul>{draft.missing.map(v=><li key={v}>{v}</li>)}</ul>:<p>No missing fields in the captured draft.</p>}</div><div className="table-scroll"><table><thead><tr><th>Work / source</th><th>Window</th><th>Engineering estimate</th><th>Planning allowance</th><th>Actual</th><th>Recorded delay</th></tr></thead><tbody>{draft.rows.map(r=><tr key={r.task_id}><td>{r.task_id} · {r.title}<small>{r.source_record||'Source ID missing'}</small></td><td>{r.window_id}</td><td>{r.planned_minutes} min</td><td>{r.planning_allowance} min</td><td>{r.actual_minutes===null?'Missing':r.actual_minutes+' min'}</td><td>{r.delay_minutes===null?'Missing':r.delay_minutes+' min'}</td></tr>)}</tbody></table></div><div className="padded"><label>Report review reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="toolbar"><button disabled={!!busy||summary.trim().length<3||reason.trim().length<3} onClick={()=>act('Draft review',()=>post(`${base}/reports/${draft.id}/review`,{summary,reason}))}>Record draft review</button><DownloadLink className="button" href={`${API}${base}/reports/${draft.id}/export`}>Export draft JSON</DownloadLink></div><p className="muted">Review does not submit an official return. Draft data is frozen; prepare another draft to incorporate later outcomes.</p></div></Panel>
}
