type Chapter={title:string;group:string;path:string;purpose:string;steps:string[];access:string};
export const chapters:Chapter[]=[
  {title:'Block queue',group:'Operations',path:'/queue',purpose:'Prioritize evidence-backed work and review maintenance recommendations.',steps:['Check evidence freshness and location mapping before selecting Recommend block plan.','Inspect the recommended window, constraints and saved schedule. An Officer records a reason and approves or rejects the recommendation.','After approved work, an Officer records actual outcomes in Reporting. Changing a recommendation requires a new review.'],access:'Planner: recommend. Officer: review recommendations.'},
  {title:'Planner',group:'Operations',path:'/planner',purpose:'Schedule maintenance into protected track-closure windows.',steps:['Select the planning network, horizon and day; choose a saved plan or generate a proposal.','Inspect work packages, unscheduled tasks, resource conflicts and solver results. Compare saved versions when needed.','An Officer validates and reviews the proposal before approval. Export the selected version as JSON or CSV for review.'],access:'Planner: generate. Officer: validate and approve.'},
  {title:'Train movements',group:'Operations',path:'/traffic',purpose:'Inspect train occupancy alongside proposed maintenance.',steps:['Use the saved snapshot to inspect the occupancy chart and station-to-station movements.','Check the relevant section and time against the proposed closure. These records are not a live train-running feed.'],access:'All roles: inspect saved records.'},
  {title:'Operations',group:'Operations',path:'/operations',purpose:'Review source evidence, cautions, blocks and incident registers.',steps:['Check source timestamps, coverage and restrictions for the selected network.','Search the saved registers and review the evidence behind a recommendation. Imported or synthetic records do not establish live operational clearance.'],access:'All roles: inspect and export. Planner: prepare evidence.'},
  {title:'Maintenance',group:'Maintenance planning',path:'/tasks',purpose:'Prepare the tasks the scheduler is allowed to plan.',steps:['Filter tasks by department, priority, section or scheduled status. Open a task to inspect its details.','Confirm location, duration, deadline, readiness and resource requirements before saving changes. Mandatory tasks must fit the model; marking a task mandatory does not create extra capacity.'],access:'All roles: inspect. Planner: add or edit tasks.'},
  {title:'Opportunities',group:'Maintenance planning',path:'/opportunities',purpose:'Find compatible work that could share a closure.',steps:['Inspect candidate combinations and their protection and resource requirements.','Review the suggested package before adding it to a proposal. Recheck the resulting schedule; an opportunity is not an approved commitment.'],access:'Planner: discover. Officer: add to a proposal.'},
  {title:'Disruption lab',group:'Maintenance planning',path:'/disruptions',purpose:'Test disruptions and compare a repaired plan with its baseline.',steps:['Create a scenario such as a shorter window, delayed freight, unavailable crew or urgent task.','Run repair and inspect changed packages, unscheduled work and retained commitments. An Officer must explicitly review commitment revisions.'],access:'Planner: create scenarios and repair. Officer: revise commitments.'},
  {title:'Availability',group:'Predictive decision support',path:'/availability',purpose:'Compare modeled asset exposure, downtime and maintenance benefit.',steps:['Select a network and saved plan, then inspect the asset-level availability estimates.','Check the assumptions and evidence before using the estimate to prioritize work. This is not a calibrated failure probability or remaining-useful-life forecast.'],access:'All roles: inspect advisory estimates.'},
  {title:'Insights',group:'Predictive decision support',path:'/insights',purpose:'Understand priority factors, historical durations and evidence confidence.',steps:['Inspect the factors and sample sizes behind each estimate; investigate stale or sparse sources.','Use narrative analysis as advisory evidence. Optional duration learning is retrospective evaluation, not a replacement for task durations or engineering review.'],access:'All roles: inspect. Planner: run analysis. Administrator: configure automation.'},
  {title:'Data review',group:'Evidence & reports',path:'/data',purpose:'Check source files and resolve locations before using imported data.',steps:['Review a CSV or JSON import preview and fix invalid or ambiguous fields.','Confirm location mappings and commit only the reviewed input. Refresh the workspace and recompute affected proposals after a source change.'],access:'All roles: inspect. Planner: import and map data.'},
  {title:'Reporting',group:'Evidence & reports',path:'/reports',purpose:'Prepare evidence-based reports for review and export.',steps:['Create a draft from the relevant recommendation and evidence. Check the source and decision history.','Select an approved recommendation and record actual execution before preparing the draft. An Officer records a draft review. Prepare a new draft for later outcomes; exports are not official railway submissions.'],access:'All roles: inspect and export. Planner: draft. Officer: record outcomes and review drafts.'},
  {title:'Results',group:'Evidence & reports',path:'/benchmarks',purpose:'Compare planning methods on the same saved inputs.',steps:['Select a saved benchmark or ask an Officer to run the four methods.','Compare feasibility, disruption performance and objective results; export the saved comparison. A benchmark is not proof of operational safety.'],access:'All roles: inspect and export. Officer: run benchmarks.'},
  {title:'Profile & security',group:'Account',path:'/profile',purpose:'Maintain your profile, sign-in username and security settings.',steps:['Update your professional details and save them. Set a unique sign-in username after your email-based account is approved.','Use Security to inspect your session and MFA policy. Access permissions explains your assigned role; changing profile details does not grant privileges.'],access:'All roles: manage their own account.'},
  {title:'User access',group:'Account',path:'/admin/users',purpose:'Review invitations, role assignments and access audit records.',steps:['An Administrator reviews the colleague and division before assigning a role.','Record the reason for each access change and inspect the audit history. Request only the access needed for the job.'],access:'Administrator only.'},
];
export const problems=[
  {title:'The planning network stays on “Loading networks”',text:'The API or its configuration may be unavailable. Retry the connection on the planning page. If it persists, contact your administrator with the time, affected URL and request ID. This guide remains readable without a planning snapshot.'},
  {title:'No saved plan or no results are shown',text:'Check the selected network, day and filters. A Planner can generate the first plan for a provisioned network. Availability needs a saved plan; Results needs a completed benchmark. An empty view is not evidence that there is no maintenance risk.'},
  {title:'An action is disabled or access is denied',text:'Check Profile & security → Access permissions. Some actions require Planner or Officer access, current inputs or a completed prior step. Ask an Administrator to review access; editing your profile cannot change your role.'},
  {title:'Evidence is stale or a proposal is no longer current',text:'Inspect source timestamps and location mappings. Refresh inputs and recompute the affected proposal, then have any changed recommendation reviewed again. Do not approve an old version just to bypass the warning.'},
  {title:'The solver cannot find a feasible plan',text:'Review mandatory tasks, readiness, deadlines, train occupancy, protection rules and resource calendars. Ask a Planner to correct inputs or reconsider the planning scope. Do not remove safety constraints simply to obtain a schedule.'},
  {title:'Username sign-in or password recovery fails',text:'Try your work email. Usernames must first be saved in your profile; username support also needs backend configuration. Password recovery uses your work email, not your username. Never send passwords, authentication codes or access tokens to support.'},
  {title:'My account is awaiting approval or asks for MFA',text:'Confirm your email and ask your division Administrator to review the account. Verified authenticator enrollment always requires MFA, even if mandatory enrollment is off. Use your authenticator or contact your organization for recovery; an unfinished setup is not enabled.'},
];
export const glossary=[
  ['Maintenance block','A protected track-closure window for work; not the freight-wagon block described in the research paper.'],
  ['Snapshot','A saved set of inputs. Check its source and timestamp; it is not automatically a live feed.'],
  ['Proposal / recommendation','A candidate decision awaiting review. Generation or validation does not equal approval.'],
  ['Validation / approval','Validation checks encoded constraints. Approval records an authorized user’s review within RailBLOX, not official track-access authority.'],
  ['Optimal / feasible / infeasible','Optimal means the encoded objective was proven best. Feasible means a valid solution was found without that proof. Infeasible means the encoded constraints cannot all be satisfied.'],
  ['Unknown / time limit','The solver may stop before proving feasibility or optimality. This is not proof that no schedule exists. Inspect the returned status and any available solution.'],
];
