import {useRef,useState} from 'react';
import {NavLink,useSearchParams} from 'react-router-dom';
import {Panel} from './components';
import {useIdentity} from './Auth';
import {PermissionsMatrix} from './PermissionsMatrix';
import {chapters,problems,glossary} from './guideContent';
import './profile.css';
import './help.css';

export function HelpPage(){
  const [params]=useSearchParams(),identity=useIdentity();
  const [search,setSearch]=useState('');const searchInput=useRef<HTMLInputElement>(null);
  const query=search.trim().toLowerCase();
  const matches=(values:string[])=>values.join(' ').toLowerCase().includes(query);
  const pages=chapters.filter(c=>matches([c.title,c.group,c.purpose,c.access,...c.steps]));
  const issues=problems.filter(p=>matches([p.title,p.text]));
  const link=(pathname:string)=>({pathname,search:params.toString()});
  return <div className="help-page">
    <div className="page-heading"><div><div className="eyebrow">USER MANUAL & HELP</div><h1>Workspace guide</h1><p>Find the right page, understand your next step and check what needs review. Available to every signed-in workspace role.</p></div></div>
    <nav className="help-contents" aria-label="Guide contents"><a href="#getting-started">Start here</a><a href="#page-directory">Page directory</a><a href="#access-help">Roles & account</a><a href="#troubleshooting">Troubleshooting</a><a href="#glossary">Terms & statuses</a><a href="#model-reference">Model & planning basis</a></nav>
    <section id="getting-started" className="help-section"><Panel title="Start here: from evidence to a reviewed plan"><div className="help-body"><p>The top navigation contains operational views. The sidebar separates maintenance planning, predictive decision support, and evidence/reporting.</p><ol className="help-steps"><li><strong>Check the evidence.</strong> Choose the planning network; review source timestamps, locations and restrictions in Operations and Data review.</li><li><strong>Decide what needs work.</strong> Use Availability and Insights as advisory evidence. Confirm task readiness in Maintenance.</li><li><strong>Prepare a proposal.</strong> Use Block queue for evidence-backed recommendations, or Planner to generate and inspect schedules. Check Train movements, packages and unscheduled work.</li><li><strong>Review the decision.</strong> An Officer validates the schedule and records the relevant approval or rejection. If inputs change, recompute and review the changed proposal.</li><li><strong>Close the loop.</strong> Record actual outcomes against approved recommendations in Reporting, then review and export the report drafts.</li></ol><p className="help-caution">RailBLOX uses synthetic or imported planning snapshots. No live COA, RTIS, REMLOT or data-logger connection is provided. A plan, risk score or approval here does not authorize train movements or track access.</p></div></Panel></section>
    <div className="help-search"><label htmlFor="guide-search">Search pages and troubleshooting</label><div><input ref={searchInput} id="guide-search" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try: import, approval, username…" aria-describedby="guide-search-results"/>{search&&<button onClick={()=>{setSearch('');searchInput.current?.focus()}}>Clear search</button>}</div><p id="guide-search-results" role="status">{query?`${pages.length} page${pages.length===1?'':'s'} and ${issues.length} troubleshooting topic${issues.length===1?'':'s'} match. Other manual sections remain available.`:'Expand a page for instructions, role requirements and a direct link.'}</p></div>
    <section id="page-directory" className="help-section"><Panel title="Page directory"><div className="help-body help-directory">{pages.length===0?<p>No pages match. Try a different term or clear the search.</p>:pages.map(c=><details key={`${c.path}:${query}`} open={query?true:undefined}><summary><span className="help-category">{c.group}</span><strong>{c.title}</strong><span className="help-summary">{c.purpose}</span></summary><div className="help-detail"><ol>{c.steps.map(step=><li key={step}>{step}</li>)}</ol><p><strong>Access:</strong> {c.access} Higher roles inherit lower-role capabilities.</p>{c.path!=='/admin/users'||identity.role==='admin'?<NavLink to={link(c.path)}>Open {c.title}</NavLink>:<p className="help-muted">Ask your Administrator to open User access.</p>}</div></details>)}</div></Panel></section>
    <section id="access-help" className="help-section"><Panel title="Roles & account"><div className="help-body"><p><strong>Viewer:</strong> inspect and export. <strong>Planner:</strong> prepare inputs and proposals. <strong>Officer:</strong> review decisions and record outcomes. <strong>Administrator:</strong> manage access and configuration. The table below lists the deployment’s capabilities.</p><h3>Sign-in and recovery</h3><p>Register with your work email, confirm it, and wait for access approval. Then set a unique username in Profile & security → Details. You can sign in with that username or your email; password recovery always uses email. Demo accounts do not support personal account changes.</p><p>Enable MFA under Security, scan the QR code and verify a code to activate it. Once enabled, new password sign-ins require your authenticator, even when mandatory enrollment is off. To turn it off, select Disable MFA and confirm with a fresh authenticator code. Division-required MFA cannot be disabled. If you lose your authenticator, contact your administrator.</p><NavLink to={link('/profile')}>Open account settings</NavLink></div><PermissionsMatrix/></Panel></section>
    <section id="troubleshooting" className="help-section"><Panel title="Troubleshooting"><div className="help-body help-faq">{issues.length===0?<p>No troubleshooting topics match. Try a different term or clear the search.</p>:issues.map(p=><details key={`${p.title}:${query}`} open={query?true:undefined}><summary>{p.title}</summary><p>{p.text}</p></details>)}<p className="help-muted">Still blocked? Contact your division Administrator. Include the page, selected network, time in IST, steps to reproduce and request ID if shown. Redact sensitive data from screenshots; never share credentials.</p></div></Panel></section>
    <section id="glossary" className="help-section"><Panel title="Terms & statuses"><dl className="help-body help-glossary">{glossary.map(([term,meaning])=><div key={term}><dt>{term}</dt><dd>{meaning}</dd></div>)}</dl></Panel></section>
    <section id="model-reference" className="help-section"><Panel title="Model & planning basis"><div className="help-body"><p>The technical chapter explains the CP-SAT scheduler, advisory estimates, assumptions, research comparison and limits. The paper’s train/block/container layers solve freight routing, not asset-maintenance planning.</p><NavLink className="button" to={link('/help/methods')}>Read Model & planning basis</NavLink><h3>Operational reference</h3><p>The CCMIS beta manual (April 2021) is a separate reference for that system, not a claim that RailBLOX implements all of its functions or current railway rules.</p><a href="https://coamis.indianrail.gov.in/Contents/CCMIS_USERMANUAL.pdf" target="_blank" rel="noreferrer">Read the official CCMIS manual (PDF)</a></div></Panel></section>
  </div>;
}
