import React from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import App from './App';
import {AuthBoundary} from './Auth';
import {ErrorBoundary} from './ErrorBoundary';
import './style.css';
import './brand.css';
const client=new QueryClient({defaultOptions:{queries:{retry:1,refetchOnWindowFocus:false}}});
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ErrorBoundary><QueryClientProvider client={client}><BrowserRouter><AuthBoundary><App/></AuthBoundary></BrowserRouter></QueryClientProvider></ErrorBoundary></React.StrictMode>);
