import {NavLink,useSearchParams} from 'react-router-dom';
import {Panel} from './components';

export function MethodsPage(){
  const [params]=useSearchParams();
  const link=(pathname:string)=>({pathname,search:params.toString()});
  return <div className="methods-page">
    <div className="page-heading"><div><div className="eyebrow">PLANNING & DECISION SUPPORT</div><h1>Model & planning basis</h1><p>Understand what is scheduled, what is estimated and what still needs human review.</p></div></div>
    <div className="method-grid">
      <Panel title="Maintenance block planning"><div className="padded"><p><strong>Question: when can this work be done?</strong></p><p>The planner assigns maintenance tasks to protected track-closure windows. It checks crew and equipment calendars, task deadlines, work compatibility, train occupancy, isolation requirements and retained commitments.</p><p>OR-Tools CP-SAT selects tasks, start times and shared work packages. Mandatory work is a hard constraint. The staged objective prioritizes an uptime proxy, then service value, plan stability during repair, and closure footprint.</p><NavLink className="button" to={link('/planner')}>Open maintenance planner</NavLink></div></Panel>
      <Panel title="Predictive decision support"><div className="padded"><p><strong>Question: what deserves attention, and why?</strong></p><p>Availability compares modeled failure exposure and planned downtime. Insights provides evidence-based priority scores, historical duration estimates and source-quality warnings.</p><p>These are advisory calculations, not a validated live failure-prediction service. The optional duration regression is an evaluation-only experiment and does not replace scheduler durations or officer approval.</p><NavLink className="button" to={link('/availability')}>Review asset availability</NavLink>{' '}<NavLink className="button" to={link('/insights')}>Review evidence insights</NavLink></div></Panel>
    </div>
    <Panel title="How to use the two workspaces"><ol className="padded"><li>Review asset health, history and evidence confidence in decision support.</li><li>Confirm maintenance tasks, locations and readiness before planning.</li><li>Generate a proposal and inspect its feasibility, unscheduled work and objective-stage results.</li><li>An Officer reviews the evidence and records approval or rejection. Capture actual outcomes for later evaluation.</li></ol><p className="padded">A risk score is not a track-access authority. An optimal solver result is optimal only for the encoded model and available inputs; it does not certify railway safety.</p></Panel>
    <Panel title="Two different meanings of block planning"><div className="padded"><p>Morganti et al. (2020), <em>Block planning for intermodal rail: Methodology and case study</em>, optimizes freight consolidation: containers on platforms, platforms in blocks, and blocks on scheduled trains. A block in that paper is a group of wagons, not a maintenance possession.</p><p>RailBLOX does <strong>not</strong> implement that paper’s MILP. Both approaches perform constrained optimization, but their decisions, capacities and objectives differ.</p><a href="https://doi.org/10.1016/j.trpro.2020.03.068" target="_blank" rel="noreferrer">Read the research paper</a></div>
      <div className="table-scroll"><table className="model-table"><thead><tr><th scope="col">Comparison</th><th scope="col">Intermodal paper</th><th scope="col">RailBLOX implementation</th></tr></thead><tbody>
        <tr><th scope="row">Decision</th><td>Select freight blocks, allocate container demand and loading platforms.</td><td>Select maintenance work, possession windows and start times.</td></tr>
        <tr><th scope="row">Solver</th><td>MILP solved with CPLEX.</td><td>CP-SAT with integer-minute intervals and independent validation.</td></tr>
        <tr><th scope="row">Capacity</th><td>Train and block lengths; container/platform loading rules.</td><td>Crew/equipment capacity, section occupancy, isolation and readiness rules.</td></tr>
        <tr><th scope="row">Objective</th><td>Block and transport costs; late, split and unserved-demand penalties.</td><td>Uptime proxy, service value, repair stability and closed-section minutes.</td></tr>
        <tr><th scope="row">Not implemented here</th><td>Three-layer train/block/container flow network.</td><td>No freight consolidation, container loading or whole-life investment-budget optimization.</td></tr>
      </tbody></table></div>
    </Panel>
    <Panel title="Asset-management strategy: useful direction, not a compliance claim"><div className="padded"><p>The supplied Network Rail strategy is dated February 2011. It emphasizes balancing service outcomes, whole-life cost and risk. RailBLOX’s evidence review, work coordination and outcome records support parts of that direction; lifecycle costs, renewal budgets and calibrated deterioration models are not implemented.</p><p><a href="https://www.scribd.com/document/529251952/NETWORK-RAIL-Asset-Management-Strategy" target="_blank" rel="noreferrer">Supplied 2011 strategy</a>{' · '}<a href="https://www.networkrail.co.uk/wp-content/uploads/2019/03/Asset-Management-Strategy.pdf" target="_blank" rel="noreferrer">Network Rail’s official 2014 strategy</a></p><p>Neither historical document demonstrates compliance with current railway requirements. Real deployment needs authorized data, reviewed engineering rules and operational acceptance.</p></div></Panel>
    <Panel title="Model limitations to check before a decision"><div className="padded"><p><strong>Availability:</strong> historical failure count divided by exposure hours is projected over the horizon and capped; fixed work-class reduction factors model the proposed benefit. These are assumptions, not calibrated individual failure probabilities or remaining useful life.</p><p><strong>Priority:</strong> weighted policy scores explain ordering, not a learned safety-risk probability. The scheduler’s additive task-level uptime proxy is not the same as maximizing the displayed asset-level net availability.</p><p><strong>Duration learning:</strong> ridge regression requires at least 30 completed outcomes with at least 20 earlier training and 10 later holdout records. Reported holdout error is retrospective, not a guarantee of future accuracy.</p><p><strong>Data:</strong> saved synthetic or imported snapshots; no live railway telemetry. Preserve source timestamps, inspect stale evidence, and record the reason for each decision.</p></div></Panel>
  </div>;
}
