import {useState} from 'react';
import {Download,Printer} from 'lucide-react';
import {Panel,Badge} from './components';
import type {Workspace} from './intelligenceTypes';
import {time} from './api';
import './traffic.css';

type Tab='Cautions'|'Blocks'|'Incident evidence';
function exportCsv(columns:string[],rows:(string|number)[][]){
  const quote=(value:string|number)=>{const text=String(value);return '"'+((/^[\s]*[=+\-@\t\r]/.test(text)?"'":'')+text).replaceAll('"','""')+'"'};
  const url=URL.createObjectURL(new Blob(['\ufeff'+[columns,...rows].map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));
  const link=document.createElement('a');link.href=url;link.download='railblox-operational-register.csv';link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function OperationalRegisters({w,day}:{w:Workspace;day:number}){
  const [tab,setTab]=useState<Tab>('Cautions'),[search,setSearch]=useState(''),[section,setSection]=useState(''),[scope,setScope]=useState('day');
  const sections=[...new Set([...w.evidence.cautions,...w.evidence.blocks,...w.evidence.history].map(row=>row.section))].sort();
  const basis=scope==='day'?`Overlaps ${time(day*1440,w.anchor,true)}–${time((day+1)*1440,w.anchor,true)} IST`:'All records in this evidence version';
  const incidents=w.evidence.history.filter(row=>(!section||row.section===section)&&`${row.id} ${row.narrative} ${row.department}`.toLowerCase().includes(search.toLowerCase())&&(scope==='all'||(Date.parse(row.completed_at)>=Date.parse(w.anchor)+day*86400000&&Date.parse(row.completed_at)<Date.parse(w.anchor)+(day+1)*86400000)));
  const periods=(tab==='Cautions'?w.evidence.cautions:w.evidence.blocks).filter(row=>(!section||row.section===section)&&`${row.id} ${row.description||''} ${row.reason||''}`.toLowerCase().includes(search.toLowerCase())&&(scope==='all'||row.start<(day+1)*1440&&row.end>day*1440));
  const columns=tab==='Incident evidence'?['Evidence','Section','Department','Completed at','Recorded delay minutes','Narrative','Evidence version']:['Record','Section','From IST','To IST','Source status','Speed limit (km/h)','Restriction / reason','Planning implication','Evidence version'];
  const rows=tab==='Incident evidence'?incidents.map(row=>[row.id,row.section,row.department,row.completed_at,row.delay_minutes,row.narrative,w.evidence.id]):periods.map(row=>[row.id,row.section,time(row.start,w.anchor,true),time(row.end,w.anchor,true),row.status||'Not supplied',row.speed_kph??'Not supplied',row.description||row.reason||'No narrative supplied',row.work_prohibited||row.planning_hold?'Excludes planned work':'Review alongside plan constraints',w.evidence.id]);
  return <Panel title="Operational registers" aside={<Badge>{w.evidence.synthetic?'Synthetic evidence':'Imported evidence'}</Badge>}><div className="register-tabs no-print" role="group" aria-label="Operational register type">{(['Cautions','Blocks','Incident evidence'] as Tab[]).map(value=><button key={value} aria-pressed={tab===value} onClick={()=>setTab(value)}>{value}</button>)}</div><div className="register-filters no-print"><label>Search register<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Record ID or description"/></label><label>Register section<select value={section} onChange={e=>setSection(e.target.value)}><option value="">All sections</option>{sections.map(value=><option key={value}>{value}</option>)}</select></label><label>Register range<select value={scope} onChange={e=>setScope(e.target.value)}><option value="day">Selected planning day</option><option value="all">All saved evidence</option></select></label><button onClick={()=>{setSearch('');setSection('');setScope('day')}}>Reset register</button><button disabled={!rows.length} onClick={()=>exportCsv(columns,rows)}><Download size={15}/>Export register CSV</button><button aria-label="Print operational register" onClick={()=>window.print()}><Printer size={15}/></button></div><p className="padded traffic-basis">{basis}. {tab==='Incident evidence'?'Historical execution narratives are supporting incident evidence, not a complete official unusual register.':'Time overlap is computed from the recorded interval. An expired interval does not prove operational cancellation or handback.'}</p><div className="table-scroll"><table><caption className="sr-only">{tab} register from evidence {w.evidence.id}</caption><thead><tr>{columns.slice(0,-1).map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.slice(0,-1).map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>{!rows.length&&<p className="empty">No matching {tab.toLowerCase()} in this range. Try all saved evidence or clear your filters.</p>}<p className="padded traffic-basis">Evidence version {w.evidence.id} · as of {new Date(w.evidence.as_of).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST.</p></Panel>
}
