import {useEffect,useState} from 'react';
import {NavLink} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {ArrowLeft,Building2,Check,Clock3,KeyRound,LockKeyhole,LogOut,Mail,MapPin,ShieldCheck,UserRound} from 'lucide-react';
import {Badge,Panel} from './components';
import {useAuthActions,useIdentity} from './Auth';
import {api} from './api';
import {PermissionsMatrix,roleNames,roleDescriptions} from './PermissionsMatrix';
import './profile.css';

type Tab='Details'|'Security'|'Access permissions'|'Activity';
const formatted=(value?:string)=>value&&!Number.isNaN(Date.parse(value))?new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})+' IST':'Not available';

export function ProfilePage(){
  const identity=useIdentity(),{changePassword,signOut,updateProfile,demo}=useAuthActions();
  const [tab,setTab]=useState<Tab>('Details'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const fromIdentity=()=>({name:identity.name||'',designation:identity.designation||'',department:identity.department||'',location:identity.location||''});
  const [draft,setDraft]=useState(fromIdentity),[saved,setSaved]=useState(fromIdentity);
  useEffect(()=>{const next=fromIdentity();setDraft(next);setSaved(next)},[identity.id,identity.name,identity.designation,identity.department,identity.location]);
  const dirty=Object.keys(draft).some(key=>draft[key as keyof typeof draft]!==saved[key as keyof typeof saved]);
  useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
  const activity=useQuery({queryKey:['account-activity',identity.id],queryFn:()=>api<{id:string;at:string;action:string;record_id:string}[]>('/api/auth/activity'),enabled:tab==='Activity'});
  const save=async(removeDob=false)=>{setBusy(true);setError('');setMessage('');try{await updateProfile(draft.name,removeDob,draft);setSaved(draft);setMessage(removeDob?'Date of birth removed from your profile.':'Profile saved.')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const initials=(identity.name||identity.email||'Demo').split(/\s+/).map(w=>w[0]).slice(0,2).join('').toUpperCase();
  return <div className="profile-page">
    <div className="page-heading"><div><div className="eyebrow"><span/>ACCOUNT SETTINGS</div><h1>Your profile</h1><p>Your professional identity, workspace access and account security.</p></div><NavLink className="button profile-return" to="/queue"><ArrowLeft size={15}/>Back to workspace</NavLink></div>
    <section className="profile-summary" aria-label="Account overview"><div className="profile-avatar" aria-hidden="true">{initials}</div><div className="profile-summary-name"><h2>{identity.name||'Demonstration account'}</h2><p>{identity.designation||'RailBLOX workspace member'}{identity.department?` · ${identity.department}`:''}</p><span><Mail size={14}/>{identity.email||'Local demonstration account'}</span></div><div className="profile-assignment"><Badge>{roleNames[identity.role]}</Badge><span><Building2 size={14}/>{identity.division}</span></div></section>
    <nav className="profile-tabs" aria-label="Profile sections">{(['Details','Security','Access permissions','Activity'] as Tab[]).map(value=><button key={value} aria-pressed={tab===value} onClick={()=>setTab(value)}>{value}</button>)}</nav>
    {message&&<div role="status" className="profile-feedback"><Check size={16}/>{message}</div>}{error&&<p role="alert" className="error">{error}</p>}
    {demo&&<p className="profile-demo">You are viewing the local demo account. Personal details and security settings become editable after signing in with a provisioned account.</p>}
    {tab==='Details'&&<div className="profile-grid"><Panel title="Professional details"><form className="profile-form" onSubmit={e=>{e.preventDefault();void save()}}><p className="profile-intro">Keep your name and working context up to date.</p><div className="profile-fields"><label>Full name<input autoComplete="name" required maxLength={120} value={draft.name} disabled={demo} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Designation<input autoComplete="organization-title" maxLength={80} value={draft.designation} placeholder="e.g. Section Engineer" disabled={demo} onChange={e=>setDraft({...draft,designation:e.target.value})}/></label><label>Department<select disabled={demo} value={draft.department} onChange={e=>setDraft({...draft,department:e.target.value})}><option value="">Select department</option>{['Engineering','Traction Distribution','Signal & Telecom','Operations','Administration'].map(d=><option key={d}>{d}</option>)}{draft.department&&!['Engineering','Traction Distribution','Signal & Telecom','Operations','Administration'].includes(draft.department)&&<option>{draft.department}</option>}</select></label><label>Office / station<input maxLength={100} value={draft.location} placeholder="Office or station name" disabled={demo} onChange={e=>setDraft({...draft,location:e.target.value})}/></label></div><p className="profile-hint"><LockKeyhole size={14}/>Profile details describe your work. Access is assigned separately by your administrator.</p><div className="profile-save"><span>{dirty?'Unsaved changes':'All changes saved'}</span><button type="button" disabled={!dirty||busy} onClick={()=>setDraft(saved)}>Discard changes</button><button disabled={demo||busy||!dirty||!draft.name.trim()} className="primary">{busy?'Saving…':'Save profile'}</button></div></form></Panel><div className="profile-side"><Panel title="Workspace membership"><div className="profile-card"><div className="profile-detail"><Building2 size={17}/><div><span>Authorized division</span><strong>{identity.division}</strong></div></div><div className="profile-detail"><ShieldCheck size={17}/><div><span>Assigned role</span><strong>{roleNames[identity.role]}</strong><p>{roleDescriptions[identity.role]}</p></div></div><div className="profile-detail"><MapPin size={17}/><div><span>Office / station</span><strong>{identity.location||'Not provided'}</strong></div></div><button className="text-button" onClick={()=>setTab('Access permissions')}>View your permissions <span aria-hidden="true">→</span></button></div></Panel><div className="profile-support"><strong>Need to update your access?</strong><p>Contact your division administrator with your account ID and the role you need.</p><NavLink to="/help">Open workspace guide</NavLink></div></div></div>}
    {tab==='Security'&&<div className="profile-grid"><Panel title="Sign-in & security"><div className="profile-card"><div className="security-item"><Mail size={20}/><div><h3>Work email</h3><p>{identity.email||'No email in demo mode'}</p><small>{identity.email_confirmed?'Email verified':demo?'Demonstration account':'Email verification status unavailable'}</small></div></div><div className="security-item"><ShieldCheck size={20}/><div><h3>Session assurance</h3><p>{demo?'Local demonstration session':identity.aal==='aal2'?'Authenticator verified':'Password session'}</p><small>{identity.mfa_required?'An authenticator is required for your operational role.':'The division security policy determines whether an authenticator is required.'}</small></div>{identity.aal==='aal2'&&<Badge tone="good">Verified</Badge>}</div><div className="security-item"><KeyRound size={20}/><div><h3>Password</h3><p>Update your password through your secure account session.</p></div><button disabled={demo||busy} onClick={changePassword}>Change password</button></div><div className="security-item"><LogOut size={20}/><div><h3>Current device</h3><p>End this browser session and clear cached workspace records.</p></div><button disabled={demo||busy} onClick={()=>void signOut()}>Sign out</button></div></div></Panel><Panel title="Account information"><dl className="profile-metadata"><div><dt>Account ID</dt><dd><code>{identity.id}</code></dd></div><div><dt>Account created</dt><dd>{formatted(identity.created_at)}</dd></div><div><dt>Last sign-in</dt><dd>{formatted(identity.last_sign_in_at)}</dd></div><div><dt>Recovery support</dt><dd>Contact your division administrator if you lose access to your authenticator.</dd></div></dl>{!demo&&<details className="profile-privacy"><summary>Personal data preferences</summary><p>Remove a birth date previously supplied during registration. Access decisions remain in the division audit trail.</p><button disabled={busy} onClick={()=>void save(true)}>Remove stored date of birth</button></details>}</Panel></div>}
    {tab==='Access permissions'&&<Panel title="Your division access" aside={<Badge>{roleNames[identity.role]}</Badge>}><p className="padded profile-intro">Permissions are cumulative. Your administrator assigns your role; the server checks it on every request. Operational approval records a planning decision within RailBLOX.</p><PermissionsMatrix/>{identity.role==='admin'&&<div className="padded"><NavLink className="button" to="/admin/users"><ShieldCheck size={16}/>Manage user access</NavLink></div>}</Panel>}
    {tab==='Activity'&&<Panel title="Your recent workspace activity" aside={<button onClick={()=>void activity.refetch()}>Refresh activity</button>}><p className="padded profile-intro">Your latest 20 recorded actions in this division. This is an operational audit view; identity-provider sign-in history is managed separately.</p>{activity.isPending&&<p className="padded" role="status">Loading activity…</p>}{activity.error&&<p className="error" role="alert">{activity.error.message}</p>}{activity.data?.length?<ol className="account-activity">{activity.data.map(event=><li key={event.id}><Clock3 size={17}/><div><strong>{event.action.replaceAll('-',' ')}</strong><code>{event.record_id}</code></div><time dateTime={event.at}>{formatted(event.at)}</time></li>)}</ol>:activity.data&&<div className="profile-empty"><UserRound size={28}/><h3>No activity recorded yet</h3><p>Your saved planning actions will appear here.</p></div>}</Panel>}
  </div>;
}
