import {useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Download,Printer,Search,TrainFront} from 'lucide-react';
import {DownloadLink} from './Auth';
import {api,API,time} from './api';
import {Panel,Badge,Sheet} from './components';
import type {Plan,Snapshot} from './types';
import './traffic.css';

type Entry={section:string;origin:string;destination:string;start:number;end:number};
type Train={id:string;kind:string;direction:string;forecast_at?:string;margin:number;occupancies:Entry[];first_entry:number;last_exit:number;section_minutes:number};
type Enquiry={snapshot_id:string;anchor:string;start:number;end:number;records:Train[];count:number;section_minutes:number;basis:string};

export function TrafficWorkspace({snapshot,plan,day}:{snapshot:Snapshot;plan:Plan;day:number}){
  const [params,setParams]=useSearchParams(),[selected,setSelected]=useState<Train|null>(null),[table,setTable]=useState(false);
  const keys=['train','direction','trainKind','origin','destination','chartHour','chartHours'];
  const set=(key:string,value:string)=>setParams(previous=>{const next=new URLSearchParams(previous);value?next.set(key,value):next.delete(key);return next});
  const reset=()=>setParams(previous=>{const next=new URLSearchParams(previous);keys.forEach(k=>next.delete(k));return next});
  const rawHour=Number(params.get('chartHour')||0), rawHours=Number(params.get('chartHours')||24);
  const hour=Number.isFinite(rawHour)?Math.max(0,Math.min(23,rawHour)):0,hours=[6,12,24].includes(rawHours)?rawHours:24;
  const start=day*1440+hour*60,end=Math.min((day+1)*1440,start+hours*60);
  const queryString=new URLSearchParams({snapshot_id:snapshot.id,start:String(start),end:String(end),search:params.get('train')||'',direction:params.get('direction')||'',kind:params.get('trainKind')||'',origin:params.get('origin')||'',destination:params.get('destination')||''}).toString();
  const query=useQuery({queryKey:['traffic',queryString],queryFn:()=>api<Enquiry>('/api/traffic/movements?'+queryString)});
  const stations=[...new Set(snapshot.sections.flatMap(s=>[s.origin,s.destination]))];
  const trains=query.data?.records||[];
  const blocks=plan.packages.filter(pack=>pack.start<end&&pack.end>start);
  const gridHeight=Math.max(240,stations.length*48),x=(minute:number)=>90+(minute-start)/(end-start)*970,y=(station:string)=>48+stations.indexOf(station)*(gridHeight-80)/Math.max(1,stations.length-1);
  return <div className="traffic-workspace">
    <div className="traffic-heading"><div><span className="section-overline">TRAIN ENQUIRY</span><h2>Movement picture</h2><p>Trace a train through the corridor and inspect the access windows around it.</p></div><Badge>Saved snapshot</Badge></div>
    <div className="traffic-filters no-print"><label><span><Search size={14}/>Train ID</span><input value={params.get('train')||''} maxLength={100} placeholder="Search trains" onChange={e=>set('train',e.target.value)}/></label><label>Direction<select value={params.get('direction')||''} onChange={e=>set('direction',e.target.value)}><option value="">Both directions</option><option value="UP">UP</option><option value="DN">DOWN</option></select></label><label>Train category<select value={params.get('trainKind')||''} onChange={e=>set('trainKind',e.target.value)}><option value="">All categories</option>{[...new Set(snapshot.movements.map(m=>m.kind))].map(kind=><option key={kind}>{kind}</option>)}</select></label><label>From station<select value={params.get('origin')||''} onChange={e=>set('origin',e.target.value)}><option value="">Any station</option>{stations.map(station=><option key={station}>{station}</option>)}</select></label><label>To station<select value={params.get('destination')||''} onChange={e=>set('destination',e.target.value)}><option value="">Any station</option>{stations.map(station=><option key={station}>{station}</option>)}</select></label><label>Chart start (IST)<select value={hour} onChange={e=>set('chartHour',e.target.value)}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Chart range<select value={hours} onChange={e=>set('chartHours',e.target.value)}>{[6,12,24].map(value=><option key={value} value={value}>{value} hours</option>)}</select></label><button onClick={reset}>Reset enquiry</button></div>
    {query.error?<div className="error" role="alert"><div><strong>Train enquiry unavailable</strong><p>{query.error.message}</p><button onClick={()=>query.refetch()}>Retry enquiry</button></div></div>:query.isPending?<div className="loading" role="status">Loading train movements…</div>:<>
    <div className="metrics traffic-metrics"><div className="metric"><span className="metric-label">Matching trains</span><strong>{query.data.count}</strong><small>{time(start,snapshot.anchor)}–{time(end,snapshot.anchor)} IST</small></div><div className="metric"><span className="metric-label">Section occupancy</span><strong>{query.data.section_minutes}<small> min</small></strong><small>Sum of matched intervals within the range</small></div><div className="metric"><span className="metric-label">Maintenance packages</span><strong>{blocks.length}</strong><small>Selected plan, within the chart range</small></div></div>
    <Panel title={table?'Movement register':'Section occupancy chart'} aside={<div className="traffic-tools no-print"><button aria-pressed={table} onClick={()=>setTable(!table)}>{table?'Show chart':'Table alternative'}</button><DownloadLink className="button" href={`${API}/api/traffic/movements/export?${queryString}`}><Download size={14}/>Export CSV</DownloadLink><button aria-label="Print train enquiry" onClick={()=>window.print()}><Printer size={15}/></button></div>}>
      <div className="traffic-legend"><span><i className="train-up"/>UP movement</span><span><i className="train-down"/>DOWN movement</span><span><i className="traffic-block"/>Proposed maintenance</span><span>Times in IST · equal station spacing</span></div>
      {!trains.length?<div className="traffic-empty"><TrainFront size={30}/><h3>No trains match this enquiry</h3><p>Adjust the date, stations or chart range. An empty snapshot is not confirmation that a line is clear.</p><button className="no-print" onClick={reset}>Clear train filters</button></div>:!table?<>
      <div className="diagram-scroll traffic-chart" tabIndex={0} role="region" aria-label="Scrollable section occupancy chart"><svg viewBox={`0 0 1100 ${gridHeight+30}`} style={{minWidth:840}} role="img" aria-label="Time versus station chart. Use the train register below to inspect each movement."><title>Saved train section occupancies and proposed maintenance windows</title>
        {Array.from({length:7},(_,index)=>{const minute=start+(end-start)*index/6;return <g key={index}><line x1={x(minute)} x2={x(minute)} y1={26} y2={gridHeight} stroke="#e0e7ee" strokeDasharray="3 4"/><text x={x(minute)} y={18} textAnchor="middle">{time(minute,snapshot.anchor)}</text></g>})}
        {stations.map(station=><g key={station}><text x={76} y={y(station)+4} textAnchor="end">{station}</text><line x1={90} x2={1060} y1={y(station)} y2={y(station)} stroke="#d9e3ec"/></g>)}
        {blocks.flatMap(pack=>pack.sections.map(sectionId=>{const section=snapshot.sections.find(s=>s.id===sectionId);if(!section)return null;return <rect key={pack.id+sectionId} x={x(Math.max(start,pack.start))} y={Math.min(y(section.origin),y(section.destination))} width={Math.max(1,x(Math.min(end,pack.end))-x(Math.max(start,pack.start)))} height={Math.max(8,Math.abs(y(section.origin)-y(section.destination)))} fill="#f3ddad" opacity=".5"><title>{pack.id} · {sectionId} · proposed maintenance</title></rect>}))}
        {trains.slice(0,100).flatMap(train=>train.occupancies.map((entry,i)=>{const clippedStart=Math.max(start,entry.start),clippedEnd=Math.min(end,entry.end),dy=y(entry.destination)-y(entry.origin),duration=entry.end-entry.start;if(duration<=0)return null;return <g key={train.id+i}><line x1={x(clippedStart)} x2={x(clippedEnd)} y1={y(entry.origin)+dy*(clippedStart-entry.start)/duration} y2={y(entry.origin)+dy*(clippedEnd-entry.start)/duration} stroke={train.direction==='UP'?'#2762a0':'#278376'} strokeWidth={3} strokeLinecap="round"><title>{train.id} · {entry.section} · {time(entry.start,snapshot.anchor)}–{time(entry.end,snapshot.anchor)}</title></line>{i===0&&<text x={x(clippedStart)+5} y={y(entry.origin)+dy*(clippedStart-entry.start)/duration-8} fill={train.direction==='UP'?'#2762a0':'#278376'}>{train.id}</text>}</g>}))}
      </svg></div>{trains.length>100&&<p className="padded">The chart shows the first 100 trains. Narrow your enquiry or use the complete CSV export.</p>}</>:null}
      {!!trains.length&&<div className="table-scroll"><table><caption className="sr-only">Matching trains; inspect a train for section entry and exit times</caption><thead><tr><th>Train</th><th>Category</th><th>Direction</th><th>First entry IST</th><th>Last exit IST</th><th>Occupancy in range</th><th>Details</th></tr></thead><tbody>{trains.map(train=><tr key={train.id}><td><strong>{train.id}</strong></td><td>{train.kind}</td><td>{train.direction}</td><td>{time(train.first_entry,snapshot.anchor,true)}</td><td>{time(train.last_exit,snapshot.anchor,true)}</td><td>{train.section_minutes} min</td><td><button className="text-button" onClick={()=>setSelected(train)} aria-label={`Inspect train ${train.id}`}>Inspect train</button></td></tr>)}</tbody></table></div>}
      <p className="padded traffic-basis">{query.data.basis} Dwell times, punctuality, speed and cancellation status are unavailable in this source contract. Maintenance overlays use the selected saved plan.</p>
    </Panel></>}
    <Sheet open={!!selected} onClose={()=>setSelected(null)} title={selected?`Train ${selected.id}`:'Train details'}>{selected&&<><Badge>{selected.kind} · {selected.direction}</Badge><h3>Saved section movements</h3><p>Protection margin: {selected.margin} minutes. These are source estimates, not confirmed train passage.</p><div className="table-scroll"><table><thead><tr><th>Section</th><th>Route</th><th>Entry IST</th><th>Exit IST</th></tr></thead><tbody>{selected.occupancies.map((entry,i)=><tr key={i}><td>{entry.section}</td><td>{entry.origin} → {entry.destination}</td><td>{time(entry.start,snapshot.anchor,true)}</td><td>{time(entry.end,snapshot.anchor,true)}</td></tr>)}</tbody></table></div><p className="traffic-basis">Snapshot {snapshot.id}. Source forecast: {selected.forecast_at?new Date(selected.forecast_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST':'Not supplied'}.</p></>}</Sheet>
  </div>;
}
